#include "krangle.h"

enum custom_keycodes {
	QMKBEST = SAFE_RANGE,
	MMACRO_0,
	MMACRO_1,
	MMACRO_2,
	MMACRO_3,
	MMACRO_4,
	MMACRO_5,
	MMACRO_6,
	MMACRO_7,
	MMACRO_8,
	MMACRO_9,
	GMACRO_1,
	GMACRO_2,
	GMACRO_3,
	GMACRO_4,
	GMACRO_5,
	GMACRO_6,
	GMACRO_7,
	GMACRO_8,
	GMACRO_9,
	GMACRO_10,
	GMACRO_11,
	GMACRO_12,
	GMACRO_13,
	GMACRO_14,
	GMACRO_15,
	GMACRO_16,
	GMACRO_17,
	GMACRO_18,
	GMACRO_19,
	GMACRO_20,
	GMACRO_21,
	GMACRO_22,
};


bool process_record_user(uint16_t keycode, keyrecord_t* record) {

	switch (keycode) {
	case MMACRO_0:
		if (record->event.pressed) {
			SEND_STRING("Your favorite piece of text");
			return false;
		}
		else {}
		break;
	case MMACRO_1:
		if (record->event.pressed) {
			SEND_STRING("\\begin{figure}[h!]" SS_TAP(X_ENT));
			SEND_STRING(SS_TAP(X_TAB) "\\centering" SS_TAP(X_SPC) SS_DELAY(20) SS_TAP(X_ENT));
			SEND_STRING("\\includegraphics[width=0.75\\textwidth]{FILENAME}" SS_TAP(X_SPC) SS_DELAY(20) SS_TAP(X_ENT));
			SEND_STRING("\\caption{CaptionText}" SS_TAP(X_SPC) SS_DELAY(20) SS_TAP(X_ENT));
			SEND_STRING("\\label{fig:}" SS_TAP(X_SPC) SS_DELAY(20) SS_TAP(X_ENT));
			SEND_STRING(SS_TAP(X_BSPC) "\\end{figure}" SS_TAP(X_SPC) SS_DELAY(20) SS_TAP(X_ENT));
			return false;
		}
		else {}
		break;
	case MMACRO_2:
		if (record->event.pressed) {
			SEND_STRING("\\begin{equation}" SS_TAP(X_SPC) SS_DELAY(20) SS_TAP(X_ENT));
			SEND_STRING("" SS_TAP(X_TAB) SS_DELAY(20) SS_TAP(X_ENT));
			SEND_STRING("\\label{eq:}" SS_TAP(X_SPC) SS_DELAY(20) SS_TAP(X_ENT));
			SEND_STRING(SS_TAP(X_BSPC) "\\end{equation}" SS_TAP(X_SPC) SS_DELAY(20) SS_TAP(X_ENT));
			return false;
		}
		else {}
		break;
	case GMACRO_1:
		if (record->event.pressed) {
			register_code(KC_RALT);
			tap_code(KC_M);
			unregister_code(KC_RALT);
			return false;
		}
		else {}
		break;
	case GMACRO_2:
		if (record->event.pressed) {
			register_code(KC_RALT);
			tap_code(KC_MINS);
			unregister_code(KC_RALT);
			return false;
		}
		else {}
		break;
	case GMACRO_3:
		if (record->event.pressed) {
			register_code(KC_LSFT);
			register_code(KC_RALT);
			tap_code(KC_M);
			unregister_code(KC_RALT);
			unregister_code(KC_LSFT);
			return false;
		}
		else {}
		break;
	}
	return true;
}

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

	KEYMAP(
		MMACRO_0, MMACRO_1, MMACRO_2, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MPRV, KC_MPLY, KC_MNXT,
		KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_1, KC_2, KC_F13, KC_F14, KC_F15, KC_F16, KC_F17, KC_F18, KC_F19, KC_F20, KC_F21, KC_F22, KC_F23, KC_F24, KC_VOLD, KC_VOLU, KC_MUTE,
		KC_7, KC_8, KC_9, KC_0, KC_1, KC_2, BL_STEP, KC_ESC, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_PSCR, KC_SLCK, KC_PAUS,
		KC_NLCK, KC_PSLS, KC_PAST, KC_PMNS, GMACRO_1, GMACRO_2, KC_BSPC, KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_EQL, KC_BSPC, KC_INS, KC_HOME, KC_PGUP,
		KC_P7, KC_P8, KC_P9, GMACRO_3, KC_4, KC_DEL, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_RBRC, KC_BSLS, KC_DEL, KC_END, KC_PGDN,
		KC_P4, KC_P5, KC_P6, KC_PPLS, KC_5, KC_6, LCTL(KC_X), KC_CAPS, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_ENT,
		KC_P1, KC_P2, KC_P3, KC_7, KC_8, LCTL(KC_C), KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_LSFT, KC_UP,
		KC_P0, KC_PDOT, KC_PENT, KC_9, KC_0, LCTL(KC_V), KC_LCTL, KC_LGUI, MO(1), KC_LALT, KC_SPC, KC_RALT, KC_RGUI, MO(2), KC_RCTL, KC_LEFT, KC_DOWN, KC_RGHT),

	KEYMAP(
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

	KEYMAP(
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

};

void matrix_init_user(void) {
}

void matrix_scan_user(void) {
}

void led_set_user(uint8_t usb_led) {

	if (usb_led & (1 << USB_LED_NUM_LOCK)) {
		DDRB |= (1 << 6); PORTB &= ~(1 << 6);
	}
	else {
		DDRB &= ~(1 << 6); PORTB &= ~(1 << 6);
	}
	if (usb_led & (1 << USB_LED_CAPS_LOCK)) {
		DDRB |= (1 << 5); PORTB &= ~(1 << 5);
	}
	else {
		DDRB &= ~(1 << 5); PORTB &= ~(1 << 5);
	}
	if (usb_led & (1 << USB_LED_SCROLL_LOCK)) {
		DDRB |= (1 << 4); PORTB &= ~(1 << 4);
	}
	else {
		DDRB &= ~(1 << 4); PORTB &= ~(1 << 4);
	}
	if (usb_led & (1 << USB_LED_COMPOSE)) {
	}
	else {
	}
	if (usb_led & (1 << USB_LED_KANA)) {
	}
	else {
	}
}